#!/bin/bash

# Initialise keyboard listener
sxhkd &

bspc config border_width        4
bspc config window_gap         12

bspc config focused_border_color "#81A1C1"
bspc config normal_border_color "#434C5E"

bspc config top_padding			15
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d А Б В Г Д Е Ж З
#bspc monitor -d α β γ δ ε ζ η θ

bspc rule -a gimp follow=on floating=on
#bspc rule -a Chromium desktop=^2 #This was literally so annoying for me

# Wallpaper
nitrogen --restore &

# Compositor
compton -b --config /home/guy/.config/compton/compton.conf &

# Fix pointer issue
xsetroot -cursor_name left_ptr

# Initialise bar
polybar main &

#xrandr --output LVDS1 --primary
#nm-applet &
