"
" Guy Nankivell, .vimrc, 2017
"

"
" Language specific attributes - some must be set before `syntax on`
"

" C
let c_space_errors = 1

" Fortran
let fortran_free_source=1
let fortran_have_tabs=1
let fortran_more_precise=1

" End language specific attributes

"
" Fundamental VIM settings
"

set nocompatible " Required for Vundle
syntax on
set number
set cursorline 
set encoding=utf-8
set mouse=a

" Make it such that when you search there is no highlighting
set nohlsearch

" Move the backup files to a designated directory
set backupdir=~/.vim/backup
set noundofile

" This allows modelines in vim
set modeline

" This makes a visible line where 80 characters is
if (exists('+colorcolumn'))
    set colorcolumn=80
    highlight ColorColumn ctermbg=9
endif

" This is super helpful. Initialise by {{{ in comment
" and terminate by }}} in another comment. 
set foldmethod=marker " can also fold by indent

"
" Colorscheme Modifications
"

" Use the below line to force compat with xterm && screen
set t_Co=256

"colorscheme solarized
"colorscheme inkstained
colorscheme nord
"colorscheme monochrome
"colorscheme nofrills-light
"colorscheme 256_noir
"colorscheme monochrome
"
let g:solarized_termcolors=256


"
" Remappings for keyboard bindings
"

" This adds virtual line navigation as opposed 
" to the usual line by line vim method
noremap <silent> <expr> j (v:count == 0 ? 'gj' : 'j')
noremap <silent> <expr> k (v:count == 0 ? 'gk' : 'k')

" Here I disabled the arrow keys so that I use hjkl
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Remaps changing vim windows by using Ctrl + h,j,k,l
" Use :vs <file> to open other workspace. 
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>


" Nerdtree toggle mapping
map <C-n> :NERDTreeToggle<CR>

" Disable the stupid help
inoremap <F1> <NOP>
noremap <F1> <NOP>

" This allows you to exit insert & visual mode by using `;;'
"imap jj <Esc>
"vmap ;; <Esc>

" This remaps bg <enter> to toggle the background colour
"map bg :let &background = ( &background == "dark"? "light" : "dark" )<CR>

"
" End Keyboard mapping changes
"

"
" Language Specific indentation tab vs space etc...
"

" Default
set tabstop=4
set softtabstop=4
set fileformat=unix

" Python
au BufNewFile,BufRead *.py,
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set smartindent |
    \ set fileformat=unix |

au BufNewFile,BufRead *.xml,
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set smartindent |
    \ set fileformat=unix |

au BufNewFile,BufRead *.html,
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set expandtab |
    \ set smartindent |
    \ set fileformat=unix |

au BufNewFile,BufRead *.c,*.h,
    \ set smartindent |
    \ set noexpandtab |
    \ set expandtab |
	\ set tabstop=8 |
    \ set shiftwidth=8 |
    \ set softtabstop=8 |
    \ set textwidth=79 |
    \ set fileformat=unix |

au BufNewFile,BufRead *.f95,*.for,
    \ set smartindent |
    \ set noexpandtab |
    \ set expandtab |
	\ set tabstop=8 |
    \ set shiftwidth=8 |
    \ set softtabstop=8 |
    \ set textwidth=79 |
    \ set fileformat=unix |

au BufNewFile,BufRead *.java,
    \ set smartindent |
    \ set noexpandtab |
    \ set expandtab |
	\ set tabstop=4 |
    \ set shiftwidth=4 |
    \ set softtabstop=4 |
    \ set textwidth=79 |
    \ set fileformat=unix |

au BufNewFile,BufRead *.lisp,*.lsp,
    \ set noexpandtab |
    \ set expandtab |
	\ set tabstop=8 |
    \ set shiftwidth=8 |
    \ set softtabstop=8 |
    \ set textwidth=79 |
    \ set fileformat=unix |

au BufNewFile,BufRead *.asm,
    \ set smartindent |
    \ set expandtab |
	\ set tabstop=8 |
    \ set shiftwidth=8 |
    \ set softtabstop=8 |
    \ set textwidth=79 |
    \ set fileformat=unix |

au BufNewFile,BufRead *.rs,
    \ set smartindent |
    \ set expandtab |
	\ set tabstop=4 |
    \ set shiftwidth=4 |
    \ set softtabstop=4 |
    \ set textwidth=79 |
    \ set fileformat=unix |

au BufNewFile,BufRead *.fs,
    \ set autoindent |
    \ set expandtab |
	\ set tabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set fileformat=unix |

