#! /bin/sh

bspc config border_width        0
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true



#bspc monitor -d 一 二 三 四 五 六 七 八 九 十 #Chinese doesn't work with Open Sans
#bspc monitor -d А Б В Г Д Е Ж З
bspc monitor -d α β γ δ ε ζ η θ

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2 #This was literally so annoying for me
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a xfce4-terminal floating=on #Looks cool, is shit.
focused_border_color "#000000"

nitrogen --restore &
compton -b --config /home/guy/.config/compton/compton.conf &
panel &
