#!/bin/bash 

#####################################################
# This script is designed to restore my home	    #
# attributes. These are typically symbolic links    #
# and directory creation. This should only be 		#
# performed after a new installation.	            #
#####################################################

# Creation of environment variables...

MYHOME="$HOME"
CURRDIR=`pwd`
DOTDIR="$(dirname "$CURRDIR")"

# Create a link from the source code directory in $home
if [ ! -d "$MYHOME"/src ] || [ ! -L "$MYHOME"/src ];
then
		ln -s /usr/local/src "$MYHOME"/src 
fi

# Create a dotfile directory in home
if [ ! -d "$MYHOME"/dotfiles ] || [ ! -L "$MYHOME"/dotfiles ];
then
		ln -s "$DOTDIR" "$MYHOME"/dotfiles 
fi

# Create an etc directory in home
if [ ! -d "$MYHOME"/etc ] || [ ! -L "$MYHOME"/etc ];
then
		ln -s $MYHOME/.config "$MYHOME"/etc 
fi
