#!/bin/sh

# Written by Guy Nankivell, 2016
# Released under the 3 clause BSD license

#####################################################
# This script is designed to restore my commonly    #
# used config files by symbolically linking them    #
# from the current directory to the target location #
# This works locally on most UNIX based OS          #
#####################################################

# Establish the platform you are working on
unamestr=`uname`
if [ "$unamestr" == 'Linux' ]; then
   PLATFORM='linux'
elif [ "$unamestr" == 'FreeBSD' ]; then
   PLATFORM='bsd'
elif [ "$unamestr" == 'DragonFly' ]; then
   PLATFORM='bsd'
else
	PLATFORM='bsd'
fi

# Creation of environment variables...

MYHOME="$HOME"
CURRDIR=`pwd`
DOTDIR="$(dirname "$CURRDIR")"

# Distro detection

if [ -f /etc/redhat-release ]
then 
	DISTRO="fedora"
fi
if [ -d /etc/pacman.d/ ]
then
	DISTRO="arch-linux"
fi

#
# This is a global check for my config directory
# Create the .config directory if it doesn't
# already exist in home
# just realised that I reference $HOME and $MYHOME
# no harm done but poor consistency
#

if [ ! -d "$MYHOME"/.config ];
then
	mkdir "$MYHOME"/.config
fi

#
# This script is designed to restore my home
# attributes. These are typically symbolic links
# and directory creation. This should only be
# performed after a new installation.
#

# Create a link from the source code directory in $home
if [ ! -d "$MYHOME"/src ] || [ ! -L "$MYHOME"/src ];
then
                ln -s /usr/local/src "$MYHOME"/src
fi

if [ ! -d "$MYHOME"/tmp ] || [ ! -L "$MYHOME"/tmp ];
then
                ln -s /tmp "$MYHOME"/tmp
fi

# Create a dotfile directory in home
#if [ ! -d "$MYHOME"/dotfiles ] || [ ! -L "$MYHOME"/dotfiles ];
#then
#               ln -s "$DOTDIR" "$MYHOME"/dotfiles
#fi

# Create an etc directory in home
if [ ! -d "$MYHOME"/etc ] || [ ! -L "$MYHOME"/etc ];
then
	ln -s $MYHOME/.config "$MYHOME"/etc
fi


#####################################################
#  _____ ____ ____  _   _ 
# |_   _/ ___/ ___|| | | |
#   | || |   \___ \| |_| |
#   | || |___ ___) |  _  |
#   |_| \____|____/|_| |_|
#                         
#####################################################

# This handles the check for my .tcshrc

if [ -L "$MYHOME"/.tcshrc ] || [ -f "$MYHOME"/.tcshrc ];
then 
	rm -r "$MYHOME"/.tcshrc
#	echo "Cleaning up old .tcshrc"
fi

# This creates the symbolic link for my .tcshrc
ln -s "$DOTDIR"/shell/tcsh/tcshrc "$MYHOME"/.tcshrc

# Important to source it so changes take effect without
# logging into the shell again
# Sends debug messages to the appropriate 
# logging location of /dev/null

#source "$MYHOME"/.tcshrc > /dev/null
#echo -e "Creating symbolic link for .tcshrc... \n"


#####################################################
# __     _____ __  __ 
# \ \   / /_ _|  \/  |
#  \ \ / / | || |\/| |
#   \ V /  | || |  | |
#    \_/  |___|_|  |_|
#
#####################################################

# This handles the check for my .vimrc

if [ -f "$MYHOME"/.vimrc ] || [ -L "$MYHOME"/.vimrc ];
then 
	rm -r "$MYHOME"/.vimrc
#	echo "Cleaning up old .vimrc"
fi

# This creates the symbolic link for my .vimrc

ln -s "$DOTDIR"/vim/vimrc "$HOME"/.vimrc

#####################################################

# This handles the check for my .vim/ directory

if [ -d "$MYHOME"/.vim ] || [ -L "$MYHOME"/.vim ];
then 
	rm -r "$MYHOME"/.vim
fi

ln -s "$DOTDIR"/vim/vim "$HOME"/.vim

#####################################################
#   ____ ___ _____ 
#  / ___|_ _|_   _|
# | |  _ | |  | |  
# | |_| || |  | |  
#  \____|___| |_|  
#                 
#####################################################

# This handles the check for my .gitconfig

if [ -f "$MYHOME"/.gitconfig ] || [ -L "$MYHOME"/.gitconfig ];
then 
	rm -r "$MYHOME"/.gitconfig
fi

ln -s "$DOTDIR"/git/config "$HOME"/.gitconfig

######################################################

# This handles the check for my .gitconfig

if [ -f "$MYHOME"/.gitignore_global ] || [ -L "$MYHOME"/.gitignore_global ];
then 
	rm -r "$MYHOME"/.gitignore_global
fi

ln -s "$DOTDIR"/git/ignore_global "$HOME"/.gitignore_global

#####################################################

# This handles the check for my .xfce/ directory

if [ -d "$MYHOME"/.config/xfce4 ] || [ -L "$MYHOME"/.config/xfce4 ];
then 
	rm -r "$MYHOME"/.config/xfce4
fi

ln -s "$DOTDIR"/xfce4 "$HOME"/.config/xfce4

#####################################################
# __          ____  __    _____ _          __  __ 
# \ \        / /  \/  |  / ____| |        / _|/ _|
#  \ \  /\  / /| \  / | | (___ | |_ _   _| |_| |_ 
#   \ \/  \/ / | |\/| |  \___ \| __| | | |  _|  _|
#    \  /\  /  | |  | |  ____) | |_| |_| | | | |  
#     \/  \/   |_|  |_| |_____/ \__|\__,_|_| |_| 
#
#####################################################

# This handles the check for my i3/ directory

if [ -d "$MYHOME"/.config/i3 ] || [ -L "$MYHOME"/.config/i3 ];
then 
	rm -r "$MYHOME"/.config/i3
fi

ln -s "$DOTDIR"/wm/i3 "$HOME"/.config/i3

#####################################################

# This handles the check for my bspwm/ directory

if [ -d "$MYHOME"/.config/bspwm ] || [ -L "$MYHOME"/.config/bspwm ];
then 
	rm -r "$MYHOME"/.config/bspwm
fi

ln -s "$DOTDIR"/wm/bspwm "$HOME"/.config/bspwm

#####################################################

# This handles the check for my sxhkd/ directory

if [ -d "$MYHOME"/.config/sxhkd ] || [ -L "$MYHOME"/.config/sxhkd ];
then 
	rm -r "$MYHOME"/.config/sxhkd
fi

ln -s "$DOTDIR"/wm/sxhkd "$HOME"/.config/sxhkd

#####################################################

# This handles the check for my compton/ directory

if [ -d "$MYHOME"/.config/compton ] || [ -L "$MYHOME"/.config/compton ];
then 
	rm -r "$MYHOME"/.config/compton
fi

ln -s "$DOTDIR"/wm/compton "$HOME"/.config/compton

#####################################################

# This handles the check for my .Xresources 
if [ -f "$MYHOME"/.Xresources ] || [ -L "$MYHOME"/.Xresources ];
then 
	rm -r "$MYHOME"/.Xresources
fi
ln -s "$DOTDIR"/wm/X/.Xresources "$HOME"/.Xresources
#xrdb "$HOME"/.Xresources

#####################################################

# SCREEN 
if [ -f "$MYHOME"/.screenrc ] || [ -L "$MYHOME"/.screenrc ];
then 
	rm -r "$MYHOME"/.screenrc
fi
ln -s "$DOTDIR"/shell/screen/screenrc "$HOME"/.screenrc

# Unsetting environment variables / cleaning up

unset MYHOME
unset DOTDIR
unset CURRDIR
unset unamestr
unset PLATFORM
unset DISTRO
exit
if [ -f /bin/tcsh ]
then
	/bin/tcsh
	source "$HOME"/.tcshrc
fi
