#!/bin/bash 

# Written by Guy Nankivell, 2016
# Released under the 3 clause BSD license

#####################################################
# This script is designed to restore my commonly    #
# used config files by symbolically linking them    #
# from the current directory to the target location	#
# This works locally in a Linux based OS.           #
#####################################################

# Establish the platform you are working on
platform='unknown'
unamestr=`uname`
if [ "$unamestr" == 'Linux' ]; then
   platform='linux'
elif [ "$unamestr" == 'FreeBSD' ]; then
   platform='freebsd'
fi

# Creation of environment variables...

MYHOME="$HOME"
CURRDIR=`pwd`
DOTDIR="$(dirname "$CURRDIR")"

# Distro detection

if [ -f /etc/redhat-release ]
then 
	DISTRO="fedora"
fi
if [ -d /etc/pacman.d/ ]
then
	DISTRO="arch-linux"
fi

# This is a global check for my config directory
# Create the .config directory if it doesn't
# already exist in home
# just realised that I reference $HOME and $MYHOME
# no harm done but poor consistency

if [ ! -d "$MYHOME"/.config ];
then
	mkdir "$MYHOME"/.config
fi

#####################################################
#  _____ ____ ____  _   _ 
# |_   _/ ___/ ___|| | | |
#   | || |   \___ \| |_| |
#   | || |___ ___) |  _  |
#   |_| \____|____/|_| |_|
#                         
#####################################################

# This handles the check for my .tcshrc

if [ -L "$MYHOME"/.tcshrc ] || [ -f "$MYHOME"/.tcshrc ];
then 
	rm -r "$MYHOME"/.tcshrc
#	echo "Cleaning up old .tcshrc"
fi

# This creates the symbolic link for my .tcshrc
# Trying for a bit of os dependence

if [[  $platform == 'linux' ]]; 
then
	ln -s "$DOTDIR"/shell/tcsh/.tcshrc "$MYHOME"/.tcshrc
else
	ln -s "$DOTDIR"/shell/tcsh/.tcshrc_bsd "$MYHOME"/.tcshrc
fi

# Important to source it so changes take effect without
# logging into the shell again
# Sends debug messages to the appropriate 
# logging location of /dev/null

#source "$MYHOME"/.tcshrc > /dev/null
#echo -e "Creating symbolic link for .tcshrc... \n"

#####################################################
# __     _____ __  __ 
# \ \   / /_ _|  \/  |
#  \ \ / / | || |\/| |
#   \ V /  | || |  | |
#    \_/  |___|_|  |_|
#
#####################################################

# This handles the check for my .vimrc

if [ -f "$MYHOME"/.vimrc ] || [ -L "$MYHOME"/.vimrc ];
then 
	rm -r "$MYHOME"/.vimrc
#	echo "Cleaning up old .vimrc"
fi

# This creates the symbolic link for my .vimrc

#echo -e "Creating symbolic link for .vimrc...\n"
ln -s "$DOTDIR"/vim/.vimrc "$HOME"/.vimrc

#####################################################

# This handles the check for my .vim/ directory

if [ -d "$MYHOME"/.vim ] || [ -L "$MYHOME"/.vim ];
then 
	rm -r "$MYHOME"/.vim
#	echo "Cleaning up old .vim directory"
fi

# This creates the symbolic link for my .tcshrc

#echo -e "Creating symbolic link for .vim/...\n"
ln -s "$DOTDIR"/vim/.vim "$HOME"/.vim

#####################################################
#   ____ ___ _____ 
#  / ___|_ _|_   _|
# | |  _ | |  | |  
# | |_| || |  | |  
#  \____|___| |_|  
#                 
#####################################################

# This handles the check for my .gitconfig

if [ -f "$MYHOME"/.gitconfig ] || [ -L "$MYHOME"/.gitconfig ];
then 
	rm -r "$MYHOME"/.gitconfig
#	echo "Cleaning up old .gitconfig..."
fi

# This creates the symbolic link for my .gitconfig

#echo -e "Creating symbolic link for .gitconfig/...\n"
ln -s "$DOTDIR"/git/.gitconfig "$HOME"/.gitconfig

######################################################

# This handles the check for my .gitconfig

if [ -f "$MYHOME"/.gitignore_global ] || [ -L "$MYHOME"/.gitignore_global ];
then 
	rm -r "$MYHOME"/.gitignore_global
#	echo "Cleaning up old .gitignore_global..."
fi

# This creates the symbolic link for my .gitconfig

#echo -e "Creating symbolic link for .gitignore_global/...\n"
ln -s "$DOTDIR"/git/.gitignore_global "$HOME"/.gitignore_global

#####################################################

# This handles the check for my .xfce/ directory

if [ -d "$MYHOME"/.config/xfce4 ] || [ -L "$MYHOME"/.config/xfce4 ];
then 
	rm -r "$MYHOME"/.config/xfce4
#	echo "Cleaning up old xfce4 directory"
fi

# This creates the symbolic link for my .git directory

#echo -e "Creating symbolic link for .xfce4/... \n"
ln -s "$DOTDIR"/xfce4 "$HOME"/.config/xfce4

#####################################################
# __          ____  __    _____ _          __  __ 
# \ \        / /  \/  |  / ____| |        / _|/ _|
#  \ \  /\  / /| \  / | | (___ | |_ _   _| |_| |_ 
#   \ \/  \/ / | |\/| |  \___ \| __| | | |  _|  _|
#    \  /\  /  | |  | |  ____) | |_| |_| | | | |  
#     \/  \/   |_|  |_| |_____/ \__|\__,_|_| |_| 
#
#####################################################

# This handles the check for my i3/ directory

if [ -d "$MYHOME"/.config/i3 ] || [ -L "$MYHOME"/.config/i3 ];
then 
	rm -r "$MYHOME"/.config/i3
#	echo "Cleaning up old compton directory"
fi

# This creates the symbolic link for my .git directory

#echo -e "Creating symbolic link for i3/... \n"
ln -s "$DOTDIR"/wm/i3 "$HOME"/.config/i3

#####################################################

# This handles the check for my bspwm/ directory

if [ -d "$MYHOME"/.config/bspwm ] || [ -L "$MYHOME"/.config/bspwm ];
then 
	rm -r "$MYHOME"/.config/bspwm
#	echo "Cleaning up old bspwm directory"
fi

# This creates the symbolic link for my .git directory

#echo -e "Creating symbolic link for .bspwm/... \n"
ln -s "$DOTDIR"/wm/bspwm "$HOME"/.config/bspwm

#####################################################

# This handles the check for my sxhkd/ directory

if [ -d "$MYHOME"/.config/sxhkd ] || [ -L "$MYHOME"/.config/sxhkd ];
then 
	rm -r "$MYHOME"/.config/sxhkd
#	echo "Cleaning up old sxhkd directory"
fi

# This creates the symbolic link for my .git directory

#echo -e "Creating symbolic link for sxhkd/... \n"
ln -s "$DOTDIR"/wm/sxhkd "$HOME"/.config/sxhkd

#####################################################

# This handles the check for my compton/ directory

if [ -d "$MYHOME"/.config/compton ] || [ -L "$MYHOME"/.config/compton ];
then 
	rm -r "$MYHOME"/.config/compton
#	echo "Cleaning up old compton directory"
fi

# This creates the symbolic link for my .git directory

#echo -e "Creating symbolic link for compton/... \n"
ln -s "$DOTDIR"/wm/compton "$HOME"/.config/compton

#####################################################

# Unsetting environment variables / cleaning up

unset MYHOME
unset DOTDIR
unset CURRDIR
unset unamestr
unset platform
unset DISTRO

