#!/bin/bash 

#####################################################
# This script is designed to restore my commonly    #
# used config files by symbolically linking them    #
# from the current directory to the target location	#
# This works locally in a Linux based OS.           #
#####################################################

# Creation of environment variables...

MYHOME="$HOME"
CURRDIR=`pwd`
DOTDIR="$(dirname "$CURRDIR")"

# This is a global check for my config directory
# Create the .config directory if it doesn't
# already exist in home
# just realised that I reference $HOME and $MYHOME
# no harm done but poor consistency

if [ ! -d "$MYHOME"/.config ];
then
	mkdir "$MYHOME"/.config
fi

#####################################################

#####   ####  ####  #   #
  #	   #      #     #	#
  #    #      ####  #####
  #    #         #  #	#
  #     ####  ####  #	#

#####################################################

# This handles the check for my .tcshrc

if [ -L "$MYHOME"/.tcshrc ] || [ -f "$MYHOME"/.tcshrc ];
then 
	rm -r "$MYHOME"/.tcshrc
	echo "Cleaning up old .tcshrc"
fi

# This creates the symbolic link for my .tcshrc

echo -e "Creating symbolic link for .tcshrc... \n"
ln -s "$DOTDIR"/shell/.tcshrc "$MYHOME"/.tcshrc

#####################################################

#     #  #   #    #
 #   #   #  # #  # #
  # #    # 	#  #   #
   #     # 	#      #

#####################################################

# This handles the check for my .vimrc

if [ -f "$MYHOME"/.vimrc ] || [ -L "$MYHOME"/.vimrc ];
then 
	rm -r "$MYHOME"/.vimrc
	echo "Cleaning up old .vimrc"
fi

# This creates the symbolic link for my .vimrc

echo -e "Creating symbolic link for .vimrc...\n"
ln -s "$DOTDIR"/.vimrc "$HOME"/.vimrc

#####################################################

# This handles the check for my .vim/ directory

if [ -d "$MYHOME"/.vim ] || [ -L "$MYHOME"/.vim ];
then 
	rm -r "$MYHOME"/.vim
	echo "Cleaning up old .vim directory"
fi

# This creates the symbolic link for my .tcshrc

echo -e "Creating symbolic link for .vim/...\n"
ln -s "$DOTDIR"/.vim "$HOME"/.vim

#####################################################

 ####   #  #####
#       #    #
#  	#   #	 #
 ####   #	 #

#####################################################

# This handles the check for my .gitconfig

if [ -f "$MYHOME"/.gitconfig ] || [ -L "$MYHOME"/.gitconfig ];
then 
	rm -r "$MYHOME"/.gitconfig
	echo "Cleaning up old .gitconfig..."
fi

# This creates the symbolic link for my .gitconfig

echo -e "Creating symbolic link for .gitconfig/...\n"
ln -s "$DOTDIR"/.gitconfig "$HOME"/.gitconfig

######################################################

# This handles the check for my .gitconfig

if [ -f "$MYHOME"/.gitignore_global ] || [ -L "$MYHOME"/.gitignore_global ];
then 
	rm -r "$MYHOME"/.gitignore_global
	echo "Cleaning up old .gitignore_global..."
fi

# This creates the symbolic link for my .gitconfig

echo -e "Creating symbolic link for .gitignore_global/...\n"
ln -s "$DOTDIR"/.gitignore_global "$HOME"/.gitignore_global

####################################################
# THIS IS FUCKING STUPID DON'T DO THIS
# This handles the check for my .git/ directory

#if [ -d "$MYHOME"/.git ];
#then 
#	rm -r "$MYHOME"/.git
#	echo "Cleaning up old .git directory"
#fi

# This creates the symbolic link for my .git directory

#echo -e "Creating symbolic link for .git/... \n"
#ln -s "$DOTDIR"/.git "$HOME"/.git

#####################################################

# This handles the check for my .xfce/ directory

if [ -d "$MYHOME"/.config/xfce4 ] || [ -L "$MYHOME"/.config/xfce4 ];
then 
	rm -r "$MYHOME"/.config/xfce4
	echo "Cleaning up old xfce4 directory"
fi

# This creates the symbolic link for my .git directory

echo -e "Creating symbolic link for .xfce4/... \n"
ln -s "$DOTDIR"/xfce4 "$HOME"/.config/xfce4

#####################################################

# This handles the check for my bspwm/ directory

if [ -d "$MYHOME"/.config/bspwm ] || [ -L "$MYHOME"/.config/bspwm ];
then 
	rm -r "$MYHOME"/.config/bspwm
	echo "Cleaning up old bspwm directory"
fi

# This creates the symbolic link for my .git directory

echo -e "Creating symbolic link for .bspwm/... \n"
ln -s "$DOTDIR"/wm/bspwm "$HOME"/.config/bspwm

#####################################################

# This handles the check for my sxhkd/ directory

if [ -d "$MYHOME"/.config/sxhkd ] || [ -L "$MYHOME"/.config/sxhkd ];
then 
	rm -r "$MYHOME"/.config/sxhkd
	echo "Cleaning up old sxhkd directory"
fi

# This creates the symbolic link for my .git directory

echo -e "Creating symbolic link for sxhkd/... \n"
ln -s "$DOTDIR"/wm/sxhkd "$HOME"/.config/sxhkd

#####################################################

# Unsetting environment variables / cleaning up

unset MYHOME
unset DOTDIR
unset CURRDIR
