#!/bin/bash 

#####################################################
# This script is designed to restore my commonly    #
# used config files by symbolically linking them    #
# from the current directory to the target location	#
# This works locally in a Linux based OS.           #
#####################################################

# Creation of environment variables...

MYHOME="$HOME"
CURRDIR=`pwd`
DOTDIR="$(dirname "$CURRDIR")"

if [ `id -u` -ne 0 ]; then
   echo "This script must be run as root" 
   exit 1
fi

# This is a global check for my config directory
# Create the .config directory if it doesn't
# already exist in home
# just realised that I reference $HOME and $MYHOME
# no harm done but poor consistency


#####################################################

#####   ####  ####  #   #
  #	   #      #     #	#
  #    #      ####  #####
  #    #         #  #	#
  #     ####  ####  #	#

#####################################################

# This handles the check for my .tcshrc

if [ -L "$"/.tcshrc ] || [ -f "$MYHOME"/.tcshrc ];
then 
	rm -r "$MYHOME"/.tcshrc
#	echo "Cleaning up old .tcshrc"
fi

# This creates the symbolic link for my .tcshrc

#echo -e "Creating symbolic link for .tcshrc... \n"

if [ -L "$MYHOME"/.tcshrc ] || [ -f "$MYHOME"/.tcshrc ];
then 
	rm -r "$MYHOME"/.tcshrc
#	echo "Cleaning up old .tcshrc"
fi

if [ -L "$MYHOME"/.tcsh_root_profile ] || [ -f "$MYHOME"/.tcsh_root_profile ];
then 
	rm -r "$MYHOME"/.tcsh_root_profile
fi
ln -s "$DOTDIR"/shell/tcsh/tcshrc "$MYHOME"/.tcshrc
ln -s "$DOTDIR"/shell/tcsh/tcsh_root_profile "$MYHOME"/.tcsh_root_profile

#####################################################

#     #  #   #    #
 #   #   #  # #  # #
  # #    # 	#  #   #
   #     # 	#      #

#####################################################

# This handles the check for my .vimrc

if [ -f "$MYHOME"/.vimrc ] || [ -L "$MYHOME"/.vimrc ];
then 
	rm -r "$MYHOME"/.vimrc
#	echo "Cleaning up old .vimrc"
fi

# This creates the symbolic link for my .vimrc

#echo -e "Creating symbolic link for .vimrc...\n"
ln -s "$DOTDIR"/vim/vimrc "$HOME"/.vimrc

#####################################################

# This handles the check for my .vim/ directory

if [ -d "$MYHOME"/.vim ] || [ -L "$MYHOME"/.vim ];
then 
	rm -r "$MYHOME"/.vim
#	echo "Cleaning up old .vim directory"
fi

# This creates the symbolic link for my .tcshrc

#echo -e "Creating symbolic link for .vim/...\n"
ln -s "$DOTDIR"/vim/vim "$HOME"/.vim


#####################################################

# This handles the check for my .screen

if [ -f "$MYHOME"/.screenrc ] || [ -L "$MYHOME"/.screenrc ];
then 
	rm -r "$MYHOME"/.screenrc
fi

ln -s "$DOTDIR"/shell/screen/screenrc "$HOME"/.screenrc


unset MYHOME
unset DOTDIR

