#!/bin/bash 

#####################################################
# This script is designed to restore my commonly    #
# used config files by symbolically linking them    #
# from the current directory to the target location	#
# This works locally in a Linux based OS.           #
#####################################################

# Creation of environment variables...

MYHOME="$HOME"
DOTDIR=`pwd`

# This is a global check for my config directory
# Create the .config directory if it doesn't
# already exist in home
# just realised that I reference $HOME and $MYHOME
# no harm done but poor consistency


#####################################################

#####   ####  ####  #   #
  #	   #      #     #	#
  #    #      ####  #####
  #    #         #  #	#
  #     ####  ####  #	#

#####################################################

# This handles the check for my .tcshrc

if [ -f "$MYHOME"/.tcshrc ];
then 
	rm -r "$MYHOME"/.tcshrc
	echo "Cleaning up old .tcshrc"
fi

# This creates the symbolic link for my .tcshrc

echo -e "Creating symbolic link for .tcshrc... \n"
ln -s "$DOTDIR"/root/.tcshrc "$MYHOME"/.tcshrc

#####################################################

#     #  #   #    #
 #   #   #  # #  # #
  # #    # 	#  #   #
   #     # 	#      #

#####################################################

# This handles the check for my .vimrc

if [ -f "$MYHOME"/.vimrc ];
then 
	rm -r "$MYHOME"/.vimrc
	echo "Cleaning up old .vimrc"
fi

# This creates the symbolic link for my .vimrc

echo -e "Creating symbolic link for .vimrc...\n"
ln -s "$DOTDIR"/.vimrc "$HOME"/.vimrc

#####################################################

# This handles the check for my .vim/ directory

if [ -d "$MYHOME"/.vim ];
then 
	rm -r "$MYHOME"/.vim
	echo "Cleaning up old .vim directory"
fi

# This creates the symbolic link for my .tcshrc

echo -e "Creating symbolic link for .vim/...\n"
ln -s "$DOTDIR"/.vim "$HOME"/.vim


unset MYHOME
unset DOTDIR

